apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-11-28T01:17:12Z"
  labels:
    app: msa-poc-basic-1
    group: com.twlife.msa.poc
    provider: fabric8
    version: 0.0.1-SNAPSHOT
  name: msa-poc-basic-1
  namespace: default
  resourceVersion: "106443"
  selfLink: /api/v1/namespaces/default/services/msa-poc-basic-1
  uid: 6c829c50-ba81-474b-97bc-83602688511e
spec:
  clusterIP: 10.111.162.154
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 31251
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: msa-poc-basic-1
    group: com.twlife.msa.poc
    provider: fabric8
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
