# ===================================================================
# Kubernetes 環境設定檔
# ===================================================================

# ----------------------------------------
# Core properties
# ----------------------------------------
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    # https://stackoverflow.com/questions/35531661
    # url: jdbc:postgresql://postgresql96:5432/msa_poc
    url: jdbc:postgresql://${K8S_POSTGRES_DB_HOST}:${K8S_POSTGRES_DB_PORT}/msa_poc
    username: ${K8S_POSTGRES_DB_USERNAME:msa_poc_mgr}
    password: ${K8S_POSTGRES_DB_PASSWORD:test123}
    validationQuery: SELECT 1
# Workaround for docker-compose startup order problems.
# docker-compose will attempt to start spanners-api before the database
# is finished initializing. By default, Spring Boot config will fail to
# start the app. continue-on-error allows it to start and retry later.
#    continue-on-error: true
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
# ----------------------------------------
# spring-cloud-kubernetes
# https://cloud.spring.io/spring-cloud-kubernetes/reference/html/appendix.html
# ----------------------------------------
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
      reload:
        enabled: true
        mode: polling
        period: 5000
      config:
        sources:
          - name: other
          - name: ${spring.application.name}
# ----------------------------------------
# Actuator 的 endpoints
# https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-endpoints
# ----------------------------------------
management:
  endpoint:
    restart:
      enabled: true
    health:
      enabled: true
    info:
      enabled: true
# ----------------------------------------
# Logging
# 使用「spring-boot-starter-logging」內建的 logback
# https://docs.spring.io/spring-boot/docs/current/reference/html/howto-logging.html
# ----------------------------------------
logging:
# 使用 Spring Boot 預設值（Log 顯示在 Console），所以將以下設定註解掉
  file: /tmp/app.log
  level:
    com.twlife.msa.poc: DEBUG
#    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
#    org.springframework.data.jpa.repository.query.SpelExpressionStringQueryParameterBinder: OFF
    org.springframework.security: INFO
