# https://github.com/spring-cloud/spring-cloud-kubernetes#service-account
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: pod-reader
  namespace: default
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: pod-reader
subjects:
  - kind: ServiceAccount
    name: config-reader
    namespace: default
  # 如果 deployment.yml 裡頭已指定 serviceAccountName: config-reader，
  # 以下的 default 就可以不用加了
  - kind: ServiceAccount
    name: default
    namespace: default