apiVersion: v1
kind: Service
metadata:
  creationTimestamp: "2019-12-04T08:24:44Z"
  labels:
    app: postgres
  name: postgres
  namespace: default
  resourceVersion: "97143"
  selfLink: /api/v1/namespaces/default/services/postgres
  uid: 50ad26a7-feaf-47f1-a02c-8012e5cf268d
spec:
  clusterIP: 10.100.215.228
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 32185
    port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: postgres
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
